### ISSUE TITLE
Bugs?

### ISSUE THREAD

**Issue by garvi-x** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#21]
I don't know if it's a mistake, but I think I have to report it.

The situation is that when I delete a device provisioning, the IoTAgent LoRaWAN remains connected to the MQTT broker. In this way, the IoTAgent continues to receive the topic updates.

```
info: New message in topic application/1/node/3738363779378704/rx
time=2018-12-12T14:30:00.110Z | lvl=DEBUG | corr=n/a | trans=n/a | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=test | subsrv=/test | msg=Looking for entity with id [clon-miniweather]. | comp=IoTAgent
time=2018-12-12T14:30:00.115Z | lvl=DEBUG | corr=n/a | trans=n/a | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=test | subsrv=/test | msg=Entity [clon-miniweather] not found. | comp=IoTAgent
time=2018-12-12T14:30:00.115Z | lvl=ERROR | corr=n/a | trans=n/a | op=IoTAgentNGSI.Alarms | srv=test | subsrv=/test | msg=Raising [MONGO-ALARM]: undefined | comp=IoTAgent
error: Error getting IoTA device object {"name":"DEVICE_NOT_FOUND","message":"No device was found with id:clon-miniweather","code":404}
```
Wouldn't it be more correct if the IoTAgent stopped the connection with the MQTT broker?

Regards, Diego

**Comment by garvi-x** [comment]
Hello again @dcalvoalonso 

On the other hand, I'm trying to use the service provisioning for subscribe my IoTAgent to the Mosquitto Broker.

First, I send a service provisioning without problems, the iotagent save the provisioning and it wait to new messages in topic. In first message received of topic, the IoTAgent create a device provisioning and it update that device in the Orion Context Broker.

The problem is that in the next message received by the IoTAgent, this generate the next messages and it don't update the entity in the Orion Context Broker.

![example](https://user-images.githubusercontent.com/15714020/49939562-80fb9900-fedd-11e8-8b57-5455cba462a4.png)

**Comment by reitsma** [comment]
The AbstractAppService attempts to maintain a list of devices. The problem is that this class is not aware of devices being provisioned or deprovisioned by calls to the nodelibagent service or by automatic provisioning from a configuration. Only after a restart of the agent it works properly, because the list is initialized on startup of the agent.

Preferably we need a callback from the nodelib library when a device is provisioned or deprovisioned, but I can't find such a call. Does it exists?

Is the additional device list really necessary to maintain the MQTT subscriptions?

**Comment by dcalvoalonso** [comment]
@garvi-x With respect to https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/issues/21#issue-390257314:
>Wouldn't it be more correct if the IoTAgent stopped the connection with the MQTT broker?

I have opened a PR to iotagent-node-lib to fix this issue: https://github.com/telefonicaid/iotagent-node-lib/pull/735. Once it is merged, I will fix this in this agent.

**Comment by dcalvoalonso** [comment]
Regarding https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/issues/21#issuecomment-446956308:

> The problem is that in the next message received by the IoTAgent, this generate the next messages and it don't update the entity in the Orion Context Broker.

It should have been fixed with https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/pull/27. @garvi-x , could you please check if it works now?

BTW, next time it would be better to create an issue for each bug. ;)

**Comment by dcalvoalonso** [comment]
@garvi-x @reitsma could you please confirm that this issue can be closed?

**Comment by garvi-x** [comment]
Hi @dcalvoalonso,

Confirm that this issue can be closed by my part. 

Just a note, when you want to delete a service provisioning as with a device provisioning (without indicate resource and apikey in the parameters) the IoTAgent returns the following message:
```
{
    "name": "MISSING_HEADERS",
    "message": "Some headers were missing from the request: [\"resource\",\"apikey\"]"
}
```

The right message would be:
```
{
    "name": "MISSING_PARAMETERS",
    "message": "Some parameters were missing from the request: [\"resource\",\"apikey\"]"
}
```

Thanks for all Daniel :))

**Comment by dcalvoalonso** [comment]
Thanks @garvi-x. I will try to fix this in https://github.com/telefonicaid/iotagent-node-lib
