### ISSUE TITLE
Property TTN payload_fields is not passed on

### ISSUE THREAD

**Issue by reitsma** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#22]
TTN has payload_raw and optionally payload_fields properties. If the payload_fields are present, no decoding is necessary anymore. Obviously, the fields property must be passed on from  from TtnAppService.preProcessMessage to the messageHandler. If not present, then the payload_raw property must be passed on.

**Comment by dcalvoalonso** [comment]
As you pointed In https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/blob/master/lib/applicationServers/ttnAppService.js#L98:

```
            if (message && message['payload_raw']) {
                this.messageHandler(this, deviceId, null, message['payload_raw']);
```

So, `payload_raw` field is always passed. Why should we pass also `payload_fields`? If I am not wrong, it is just the same information transmitted with `payload_raw` but unencrypted, isn't it?

**Comment by reitsma** [comment]
Payload_raw is the base64-encoded payload (no encryption). This payload is encoded in some way. In TTN the knowledge of the encoding/decoding algorithm may be restricted to the TTN application, i.e. inside the TTN platform. The MQTT client does not necessarily know how to decode. In our case, the encoding algorithm was proprietary. Fortunately, there is this payload_fields object. So, I think you should pass it. I don't know how it matches cayenne or cbor with the known encodings, I don't have sensors around to test.

**Comment by dcalvoalonso** [comment]
Sorry, I made a mistake, you're right, `payload_raw` does not contain encrypted information.

Nevertheless:
> This payload is encoded in some way. In TTN the knowledge of the encoding/decoding algorithm may be restricted to the TTN application, i.e. inside the TTN platform.
The encoding/decoding algorithm is not restricted to the TTN but the sensor/device provider/developer.  In your devices' application, you can decide the payload format that you want to use. Then, in TTN console you can define if the payload format is CayenneLPP or a custom one. For this reason, when you do the device /service provisioning you can specify the `data_model`.

As you can see, we don't need to pass `payload_fields` because we are actually obtaining this value by decoding the `payload_raw`. The advantage of our approach is that the IoT Agent capabilities in this sense are beyond TTN, supporting an additional payload format (i.e. CBOR). Our intention is to add more payload formats in the future and any developer can easily add proprietary solutions by forking the agent.

**Comment by reitsma** [comment]
All well, but sometimes the payload decoding algorithm is proprietary and not available for the agent developer. That is my case. I do not have access to that algorithm, I need the payload_fields.

**Comment by dcalvoalonso** [comment]
Just to understand your use-case, if you don't have access to the payload decoding algorithm, how the TTN application server is aware of it?

**Comment by reitsma** [comment]
The TTN application server is aware of the payload decoding algorithm, but the application owner has only given me an access key for subscribing to the MQTT topics of the application. A strict role separation so to say.

**Comment by dcalvoalonso** [comment]
@reitsma  could you please check if this issue can be closed? Thanks! :)

**Comment by reitsma** [comment]
This issue is now solved with your fix. Thanks!

**Comment by dcalvoalonso** [comment]
Thanks for the feedback!
