### ISSUE TITLE
DeviceEui is not passed on

### ISSUE THREAD

**Issue by reitsma** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#23]
For automatic device provisioning (through a device group configuration), the device_eui is used to lookup the device. Although in TtnAppService.ttpreProcessMessage deviceId and deviceEui are the same by convention, the deviceEui is not forwarded to the message handler. The device is registered without deviceEui set. 

By more analyzing I cannot determine when it becomes really an issue, but it seems incorrect. O I see, the lookup call is used only by the loraserverio.

The root cause of many problems with provisioning and deprovisioning is caused by the parallel management of device lists. See issue #21.

**Comment by dcalvoalonso** [comment]
For TTN, as you can see in https://www.thethingsnetwork.org/docs/applications/mqtt/api.html, the MQTT API for uplink messages does not contain or passes the `deviceEui`.
This is not the case of LoRaServer.io, from https://www.loraserver.io/lora-app-server/integrate/sending-receiving/mqtt/:

> Uplink: application/[applicationID]/device/[devEUI]/rx

Thus, in the latter case, we are able to pass this information when the device has not been provisioned previously.

I have reviewed the functionality and I don't find any bug or issue caused by not passing the `deviceEui` in the case of TTN. Have you found some problems?

**Comment by dcalvoalonso** [comment]
>  I think in TTN the device id is de facto the device EUI

Please find attached an screenshot from TTN console:
![ttn_console](https://user-images.githubusercontent.com/11388886/50840819-a73d1900-1363-11e9-820b-36ef23b90adc.png)

As you can see the Device ID (lora-n-001) is different from the Device EUI (3339343752356A14).

This is also explained in https://www.thethingsnetwork.org/docs/devices/registration.html:

> For Device ID, choose a - for this application - unique ID of lower case, alphanumeric characters and nonconsecutive - and _.
For Device EUI, copy-paste the one you retrieved from your device.

**Comment by dcalvoalonso** [comment]
Fixed with #54 . @reitsma could you please check and close the issue?

**Comment by dcalvoalonso** [comment]
I close the issue as it is solved with #54. @reitsma, you can reopen it if you consider necessary.
